### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by rwitinokhuber** [erhs-r/group_6#4]
- [  ] All data for our project has been uploaded 
- [  ] Upload Colorado data on covid cases and deaths by county 
- [  ] Upload Colorado data on political affiliations by county 
- [  ] Upload Colorado data on SES by county

**Comment by kaileejreed** [comment]
@rwitinokhuber - quick question: did you mean county or country for the 2nd and 3rd bullets? I can help with this in terms of loading the data in 😊

**Comment by rwitinokhuber** [comment]
@kaileejreed - thanks for catching that, county!

**Comment by kaileejreed** [comment]
@rwitinokhuber - I assumed so 😉 I just wanted to be sure. I can upload data once we have things more organized (?) Maybe just have a data folder with these three datasets within it? I am sure you guys talked about this today - so I am sorry if that is the case.

**Comment by rwitinokhuber** [comment]
@kaileejreed - I think I just added a branch called Data. I uploaded a .csv with PCR in Larimer county since March. Let me know if you have access to it. If so, can we use this? I'm not sure exactly how to create folders in GitHub, I thought it was through a repository until I realized the repository was the project. 

Not to worry about today, we kept our discussion brief and can go into more detail during our next meeting. I hope all is okay with your furry friend!

**Comment by kaileejreed** [comment]
@rwitinokhuber - that is exactly what I meant! I have access and it looks great so far - nice work!
Thank you so much ☺️

**Comment by kaileejreed** [comment]
We are planning to focus on Larimer County by clustering positive cases with socioeconomic status/we think this could be easier than what we are planning :) Let us know what you think @rwitinokhuber

**Comment by rwitinokhuber** [comment]
Sounds good! I'm sending an email to you both now! So sorry I missed class. @kaileejreed @bwenck
