### ISSUE TITLE
Group Tasks

### ISSUE THREAD

**Issue by rwitinokhuber** [erhs-r/group_6#7]
- [x] Upload all datasets (ses, covid cases/deaths, state policy)
- [x] Tidy data for analysis (Tidyverse -> get to averages by city)
- [x] Analyze data including
1.  - [x] Map of Larimer county with cities as polygons (fips)
2. -  [x] Income dataset: For each city show income, poverty, popn density by fip
3. - [x] LC cases and deaths datasets: by city
4. - [x] Scatterplot of average ses across place compared to avg
5. - [x] Scatterplot of cases and deaths across place compared to avg
5. - [x] Pull in Tigris census data to compare (Brooke's example on leaflet from Denver -> change from Denver to 
            Larimer) 
           - If align then we can just do a leftjoin (use stringr to clean and match)
6.  - [x] Try to find a spatial file (a. take Tigris files on census tracks and pair with fips codes; b. 
             which census tracks are inside certain cities by getting spatial files from cities; c. 
              groupby city; d. spatial computation book; e. see which census tracks fall within each city)
- [x] Create Flexboard
- [x] Create powerpoint
- [x] Presentation

**Comment by rwitinokhuber** [comment]
Links from Brooke from Tigris: 
- looking to find shapes for city boundaries
- use geospatial joins

https://geocompr.robinlovelace.net/spatial-operations.html 

https://journal.r-project.org/archive/2016/RJ-2016-043/RJ-2016-043.pdf

- urban areas
- metro area functions

**Comment by kaileejreed** [comment]
Nice work everyone and thank you for your awesome maps!
